name: example
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # BSD License
  path_provider: ^0.4.1

  # BSD License
  flutter_downloader: 1.1.7

  mapsforge_flutter:
    path: ../mapsforge_flutter

  # BSD License
  logging: ^0.11.3+2

  # MIT License
  dcache: #0.2.1
    git:
      url: https://github.com/mikes222/dcache
    # path: ../../github_dcache

  # MIT License
  xml: 3.4.1

  # Apache 2.0 License
  rxdart: "0.21.0"

  # BSD License
  synchronized: 2.1.0

  flutter_svg: 0.13.0+2

  image: 2.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/defaultrender.xml
   - assets/patterns/coniferous.svg
   - assets/patterns/coniferous_and_deciduous.svg
   - assets/patterns/deciduous.svg
   - assets/patterns/farmland.svg
   - assets/patterns/grass.svg
   - assets/patterns/hills.svg
   - assets/patterns/quarry.svg
   - assets/patterns/scrub.svg
   - assets/patterns/swamp.svg
   - assets/patterns/access-destination.png
   - assets/patterns/access-private.png
   - assets/patterns/arrow.png
   - assets/patterns/cemetery.png
   - assets/patterns/coniferous.svg
   - assets/patterns/coniferous_and_deciduous.svg
   - assets/patterns/deciduous.svg
   - assets/patterns/dot.png
   - assets/patterns/farmland.svg
   - assets/patterns/grass.svg
   - assets/patterns/hills.svg
   - assets/patterns/marsh.png
   - assets/patterns/military.png
   - assets/patterns/nature-reserve.png
   - assets/patterns/pike.png
   - assets/patterns/quarry.svg
   - assets/patterns/rail.png
   - assets/patterns/scrub.svg
   - assets/patterns/swamp.svg
   - assets/patterns/wood-coniferous.png
   - assets/patterns/wood-deciduous.png
   - assets/patterns/wood-mixed.png
   - assets/symbols/bench.svg
   - assets/symbols/cable_car.svg
   - assets/symbols/chair_lift.svg
   - assets/symbols/dot_black.svg
   - assets/symbols/dot_blue.svg
   - assets/symbols/dot_blue_dark.svg
   - assets/symbols/dot_magenta.svg
   - assets/symbols/dot_white.svg
   - assets/symbols/gondola.svg
   - assets/symbols/oneway.svg
   - assets/symbols/peak.svg
   - assets/symbols/railway-crossing-small.svg
   - assets/symbols/railway-crossing.svg
   - assets/symbols/traffic_signal.svg
   - assets/symbols/volcano.svg
   - assets/symbols/accommodation/alpinehut.svg
   - assets/symbols/accommodation/camping.svg
   - assets/symbols/accommodation/caravan_park.svg
   - assets/symbols/accommodation/chalet.svg
   - assets/symbols/accommodation/hostel.svg
   - assets/symbols/accommodation/hotel2.svg
   - assets/symbols/accommodation/shelter2.svg
   - assets/symbols/amenity/firestation3.svg
   - assets/symbols/amenity/fountain2.svg
   - assets/symbols/amenity/library.svg
   - assets/symbols/amenity/playground.svg
   - assets/symbols/amenity/police2.svg
   - assets/symbols/amenity/post_box.svg
   - assets/symbols/amenity/post_office.svg
   - assets/symbols/amenity/recycling.svg
   - assets/symbols/amenity/telephone.svg
   - assets/symbols/amenity/toilets.svg
   - assets/symbols/barrier/blocks.svg
   - assets/symbols/barrier/bollard.svg
   - assets/symbols/barrier/cycle_barrier.svg
   - assets/symbols/barrier/gate.svg
   - assets/symbols/barrier/lift_gate.svg
   - assets/symbols/barrier/stile.svg
   - assets/symbols/custom/amenity/fountain2.svg
   - assets/symbols/custom/amenity/library.svg
   - assets/symbols/custom/amenity/toilets.svg
   - assets/symbols/custom/money/atm2.svg
   - assets/symbols/custom/tourist/archaeological2.svg
   - assets/symbols/custom/tourist/attraction.svg
   - assets/symbols/custom/tourist/castle2.svg
   - assets/symbols/custom/tourist/cinema2.svg
   - assets/symbols/custom/tourist/information.svg
   - assets/symbols/custom/tourist/memorial.svg
   - assets/symbols/custom/tourist/monument.svg
   - assets/symbols/custom/tourist/museum.svg
   - assets/symbols/custom/tourist/ruin.svg
   - assets/symbols/custom/tourist/theatre.svg
   - assets/symbols/custom/tourist/view_point.svg
   - assets/symbols/custom/tourist/windmill.svg
   - assets/symbols/custom/tourist/zoo.svg
   - assets/symbols/education/nursery3.svg
   - assets/symbols/education/school.svg
   - assets/symbols/education/university.svg
   - assets/symbols/food/bar.svg
   - assets/symbols/food/biergarten.svg
   - assets/symbols/food/cafe.svg
   - assets/symbols/food/drinkingtap.svg
   - assets/symbols/food/fastfood.svg
   - assets/symbols/food/pub.svg
   - assets/symbols/food/restaurant.svg
   - assets/symbols/health/doctors2.svg
   - assets/symbols/health/hospital.svg
   - assets/symbols/health/pharmacy.svg
   - assets/symbols/money/atm2.svg
   - assets/symbols/money/bank2.svg
   - assets/symbols/place_of_worship/buddhist.svg
   - assets/symbols/place_of_worship/christian.svg
   - assets/symbols/place_of_worship/hindu.svg
   - assets/symbols/place_of_worship/islamic.svg
   - assets/symbols/place_of_worship/jewish.svg
   - assets/symbols/place_of_worship/shinto.svg
   - assets/symbols/place_of_worship/unknown.svg
   - assets/symbols/poi/cave.svg
   - assets/symbols/poi/embassy2.svg
   - assets/symbols/poi/mountain_pass.svg
   - assets/symbols/shopping/alcohol.svg
   - assets/symbols/shopping/bakery.svg
   - assets/symbols/shopping/bicycle.svg
   - assets/symbols/shopping/book.svg
   - assets/symbols/shopping/butcher.svg
   - assets/symbols/shopping/car_repair.svg
   - assets/symbols/shopping/convenience.svg
   - assets/symbols/shopping/diy.svg
   - assets/symbols/shopping/greengrocer.svg
   - assets/symbols/shopping/laundrette.svg
   - assets/symbols/shopping/marketplace.svg
   - assets/symbols/shopping/supermarket.svg
   - assets/symbols/sport/golf.svg
   - assets/symbols/sport/shooting.svg
   - assets/symbols/sport/soccer.svg
   - assets/symbols/sport/stadium.svg
   - assets/symbols/sport/swimming_outdoor.svg
   - assets/symbols/sport/tennis.svg
   - assets/symbols/tourist/archaeological2.svg
   - assets/symbols/tourist/attraction.svg
   - assets/symbols/tourist/castle2.svg
   - assets/symbols/tourist/cinema2.svg
   - assets/symbols/tourist/information.svg
   - assets/symbols/tourist/memorial.svg
   - assets/symbols/tourist/monument.svg
   - assets/symbols/tourist/museum.svg
   - assets/symbols/tourist/picnic.svg
   - assets/symbols/tourist/ruin.svg
   - assets/symbols/tourist/theatre.svg
   - assets/symbols/tourist/view_point.svg
   - assets/symbols/tourist/windmill.svg
   - assets/symbols/tourist/zoo.svg
   - assets/symbols/transport/airport2.svg
   - assets/symbols/transport/bus_station.svg
   - assets/symbols/transport/bus_stop.svg
   - assets/symbols/transport/fuel.svg
   - assets/symbols/transport/helicopter.svg
   - assets/symbols/transport/lighthouse.svg
   - assets/symbols/transport/parking.svg
   - assets/symbols/transport/parking_private.svg
   - assets/symbols/transport/rental_bicycle.svg
   - assets/symbols/transport/slipway.svg
   - assets/symbols/transport/traffic_lights.svg
   - assets/symbols/transport/train_station2.svg
   - assets/symbols/transport/tram_stop.svg
   - assets/symbols/water/weir.svg


  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
