name: mapsforge_indoor_example
description: Example app to demonstrate mapsforge indoor capabilites.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
 sdk: ">=2.2.2 <3.0.0"

dependencies:
 flutter:
  sdk: flutter

 # BSD License, transitive dependency
 path_provider: ^2.0.1

 # MIT License
 dio: ^4.0.0

 mapsforge_flutter:
  path: ../mapsforge_flutter

 # BSD License
 logging: ^1.0.1

 # Apache 2.0 License, transitive dependency
 rxdart: 0.27.0

dev_dependencies:
 flutter_test:
  sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

 # The following line ensures that the Material Icons font is
 # included with your application, so that you can use the icons in
 # the material Icons class.
 uses-material-design: true

 # To add assets to your application, add an assets section, like this:
 assets:
  - assets/custom.xml
  - assets/icons/stairs.svg
  - assets/icons/wc.svg
  - assets/icons/wc_female.svg
  - assets/icons/wc_male.svg
  - assets/icons/elevator.svg
  - assets/icons/shop.svg
  - assets/icons/restaurant.svg
  - assets/icons/parking.svg
  - assets/icons/exit.svg
  - assets/icons/escape.svg
  - assets/icons/entrance.svg
